import os

class Oculus_Visualizer:
    """
    OCULUS VISUALIZER: The Architect's Canvas.
    Enforces Law 250: Building visual workflow diagrams.
    """
    
    def __init__(self, output_dir):
        self.output_dir = output_dir

    def draw_map(self, nodes, edges, title="Target Architecture"):
        """
        Generates a modern, dark-themed HTML visualization using Mermaid.js.
        """
        mermaid_graph = "graph TD\n"
        
        # Style definitions for "Modern Dark Theme"
        # We'll use the default dark theme of mermaid but custom classes can be added
        mermaid_graph += "    classDef node fill:#1a1a1a,stroke:#00ff9d,stroke-width:2px,color:#fff,font-family:Arial;\n"
        
        for node in nodes:
            # Sanitize node ID to be safe for Mermaid
            nid = self._sanitize(node)
            mermaid_graph += f"    {nid}({node}):::node\n"
            
        for source, target in edges:
            sid = self._sanitize(source)
            tid = self._sanitize(target)
            mermaid_graph += f"    {sid} --> {tid}\n"

        html_content = f"""
<!DOCTYPE html>
<html>
<head>
    <title>{title} - Zohar Map</title>
    <style>
        body {{ background-color: #0d1117; color: #c9d1d9; font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; display: flex; flex-direction: column; align-items: center; padding: 20px; }}
        .container {{ width: 90%; max-width: 1200px; background: #161b22; border: 1px solid #30363d; border-radius: 6px; padding: 20px; box-shadow: 0 4px 12px rgba(0,0,0,0.5); }}
        .mermaid {{ width: 100%; display: flex; justify-content: center; margin-top: 20px; }}
        h1 {{ color: #58a6ff; border-bottom: 1px solid #30363d; padding-bottom: 10px; width: 100%; text-align: center; }}
        .footer {{ margin-top: 20px; font-size: 0.8em; color: #8b949e; }}
    </style>
</head>
<body>
    <div class="container">
        <h1>{title}</h1>
        <div class="mermaid">
{mermaid_graph}
        </div>
        <div class="footer">Generated by Zohar Toolkit | The Architect's Canvas (Law 250)</div>
    </div>
    <script type="module">
        import mermaid from 'https://cdn.jsdelivr.net/npm/mermaid@10/dist/mermaid.esm.min.mjs';
        mermaid.initialize({{ 
            startOnLoad: true, 
            theme: 'dark',
            securityLevel: 'loose',
            themeVariables: {{
                primaryColor: '#1a1a1a',
                primaryTextColor: '#fff',
                primaryBorderColor: '#00ff9d',
                lineColor: '#58a6ff',
                secondaryColor: '#0d1117',
                tertiaryColor: '#161b22'
            }}
        }});
    </script>
</body>
</html>
"""
        output_path = os.path.join(self.output_dir, "Workflow_Map.html")
        with open(output_path, 'w', encoding='utf-8') as f:
            f.write(html_content)
            
        print(f"[OCULUS] Visual Map generated at: {output_path}")
        return output_path

    def _sanitize(self, text):
        return text.replace(" ", "_").replace(".", "_").replace("-", "_").replace(":", "_").replace("/", "_")
