import requests
from bs4 import BeautifulSoup
from fpdf import FPDF
import datetime
import os

# --- CONFIGURATION ---
TARGET_URL = "https://bishopzorak.com/"
OUTPUT_PDF = "c:/Users/kille/Documents/trae_projects/osint_links/Intelligence_Reports/BISHOP_ZORAK_SECURITY_AUDIT.pdf"

# --- VULNERABILITY DATABASE (PASSIVE) ---
findings = []

def check_headers(headers):
    """Checks for missing security headers."""
    security_headers = {
        "Strict-Transport-Security": "Missing HSTS (HTTP Strict Transport Security). Man-in-the-Middle risk.",
        "Content-Security-Policy": "Missing CSP. High risk of XSS (Cross-Site Scripting).",
        "X-Frame-Options": "Missing X-Frame-Options. Vulnerable to Clickjacking.",
        "X-Content-Type-Options": "Missing X-Content-Type-Options. Risk of MIME-sniffing attacks.",
        "Referrer-Policy": "Missing Referrer-Policy. Potential data leakage.",
        "Permissions-Policy": "Missing Permissions-Policy. Unrestricted browser feature access."
    }

    for header, warning in security_headers.items():
        if header not in headers:
            findings.append({"severity": "Medium", "issue": f"Missing Header: {header}", "desc": warning})
        else:
            print(f"[+] Found {header}")

    # Check for Information Leakage
    if "Server" in headers:
        findings.append({"severity": "Low", "issue": "Information Leakage: Server Header", "desc": f"Server version exposed: {headers['Server']}. Attackers can target specific version exploits."})
    if "X-Powered-By" in headers:
        findings.append({"severity": "Low", "issue": "Information Leakage: X-Powered-By", "desc": f"Tech stack exposed: {headers['X-Powered-By']}."})

def check_files():
    """Checks for exposed sensitive files."""
    files = ["robots.txt", "sitemap.xml", "admin", "wp-admin", "login"]
    
    for file in files:
        url = f"{TARGET_URL.rstrip('/')}/{file}"
        try:
            r = requests.get(url, timeout=5)
            if r.status_code == 200:
                if "admin" in file or "login" in file:
                     findings.append({"severity": "High", "issue": f"Exposed Admin Panel: /{file}", "desc": "Admin login page is publicly accessible. Susceptible to Brute Force."})
                else:
                    findings.append({"severity": "Info", "issue": f"Exposed File: /{file}", "desc": "Publicly accessible information file. May reveal site structure."})
        except:
            pass

def generate_pdf():
    pdf = FPDF()
    pdf.add_page()
    
    # Title
    pdf.set_font("Arial", 'B', 16)
    pdf.cell(0, 10, "SECURITY AUDIT REPORT: BISHOPZORAK.COM", 0, 1, 'C')
    pdf.set_font("Arial", 'I', 10)
    pdf.cell(0, 10, f"Generated by Zophiel Intelligence | Date: {datetime.date.today()}", 0, 1, 'C')
    pdf.ln(10)

    # Executive Summary
    pdf.set_font("Arial", 'B', 12)
    pdf.cell(0, 10, "1. EXECUTIVE SUMMARY", 0, 1)
    pdf.set_font("Arial", '', 10)
    pdf.multi_cell(0, 10, "A passive security assessment was performed on https://bishopzorak.com/. This audit utilized non-intrusive reconnaissance techniques to identify configuration weaknesses, information leakage, and potential attack vectors without executing active exploits.")
    pdf.ln(5)

    # Methodology
    pdf.set_font("Arial", 'B', 12)
    pdf.cell(0, 10, "2. METHODOLOGY", 0, 1)
    pdf.set_font("Arial", '', 10)
    pdf.multi_cell(0, 10, "- Header Analysis: Inspection of HTTP response headers for security policies.\n- Information Leakage: Identification of exposed version numbers and tech stacks.\n- Endpoint Enumeration: Checking for common exposed files (robots.txt, admin panels).")
    pdf.ln(5)

    # Findings
    pdf.set_font("Arial", 'B', 12)
    pdf.cell(0, 10, "3. VULNERABILITY FINDINGS", 0, 1)
    
    if not findings:
        pdf.set_font("Arial", '', 10)
        pdf.cell(0, 10, "No obvious vulnerabilities found via passive scan.", 0, 1)
    else:
        for item in findings:
            # Color coding
            if item['severity'] == "High":
                pdf.set_text_color(255, 0, 0)
            elif item['severity'] == "Medium":
                pdf.set_text_color(255, 128, 0)
            else:
                pdf.set_text_color(0, 0, 0)
            
            pdf.set_font("Arial", 'B', 10)
            pdf.cell(0, 10, f"[{item['severity']}] {item['issue']}", 0, 1)
            pdf.set_text_color(0, 0, 0)
            pdf.set_font("Arial", '', 10)
            pdf.multi_cell(0, 5, f"Details: {item['desc']}\n")
            pdf.ln(2)

    # Recommendations
    pdf.ln(5)
    pdf.set_font("Arial", 'B', 12)
    pdf.cell(0, 10, "4. HARDENING RECOMMENDATIONS", 0, 1)
    pdf.set_font("Arial", '', 10)
    recommendations = """
1. IMPLEMENT SECURITY HEADERS:
   - Add 'Strict-Transport-Security' (HSTS) to enforce HTTPS.
   - Add 'Content-Security-Policy' (CSP) to prevent XSS.
   - Add 'X-Frame-Options: DENY' to prevent Clickjacking.

2. OBSCURE SERVER INFORMATION:
   - Configure the web server (Nginx/Apache) to hide the 'Server' version.
   - Remove 'X-Powered-By' headers (e.g., PHP, Express).

3. PROTECT ADMIN PANELS:
   - If an admin panel exists, restrict access by IP address.
   - Implement Rate Limiting to prevent brute force attacks.
    """
    pdf.multi_cell(0, 5, recommendations)

    # Footer / Disclaimer
    pdf.ln(10)
    pdf.set_font("Arial", 'I', 8)
    pdf.multi_cell(0, 5, "DISCLAIMER: This report is for educational and defensive purposes only. The findings are based on public information. No unauthorized access was attempted.")

    pdf.output(OUTPUT_PDF)
    print(f"PDF generated at: {OUTPUT_PDF}")

def run_audit():
    print(f"[*] Starting Passive Audit on {TARGET_URL}...")
    try:
        r = requests.get(TARGET_URL, timeout=10)
        print(f"[*] Status Code: {r.status_code}")
        check_headers(r.headers)
        check_files()
        generate_pdf()
        
        # Print summary to console for the AI to read
        print("\n--- FINDINGS SUMMARY ---")
        for f in findings:
            print(f"- [{f['severity']}] {f['issue']}")
            
    except Exception as e:
        print(f"[!] Error: {e}")

if __name__ == "__main__":
    run_audit()
